import { Poppins } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import SidebarRight from "./components/sidebarRight";
const poppins = Poppins({
  weight: ["300", "400", "700"], // light, regular, bold
  subsets: ["latin"],
  variable: "--font-poppins",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Subesh Yadav Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <head>
      <link rel="icon" href="/logo.svg" />
      </head>
      <body
        className={`${poppins.variable}  antialiased ` }
      >
       <div className="flex">
        <div className="w-[50px] ">
          <Sidebar />
        </div>

        <div className="flex-1">
          {children}
          <footer className="flex pb-5 text-[#90A0D9] justify-center items-center ">
            <p>No pain, No gain!</p>
            </footer>
        </div>

        <div className="w-[50px] ">
          <SidebarRight />
        </div>
      </div>
      </body>
    </html>
  );
}
